---
apiVersion: v1
kind: Service
metadata:
  name: esthesis-platform-ui-service
spec:
  selector:
    app: esthesis-platform-ui
  ports:
    - port: 80
      nodePort: 32000
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: esthesis-is-mqtt-cert-service
spec:
  selector:
    app: esthesis-is-mqtt-cert
  ports:
    - port: 8883
      nodePort: 32004
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: esthesis-platform-proxy-provisioning-service
spec:
  selector:
    app: esthesis-platform-proxy-provisioning
  ports:
    - port: 80
      nodePort: 32005
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: esthesis-platform-proxy-registration-service
spec:
  selector:
    app: esthesis-platform-proxy-registration
  ports:
    - port: 80
      nodePort: 32006
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: esthesis-platform-proxy-dt-service
spec:
  selector:
    app: esthesis-platform-dt-registration
  ports:
    - port: 80
      nodePort: 32007
  type: NodePort
