apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../platform-services
  - ../../datasinks
  - ../../platform-proxy
  - ../../platform
  - ../../ingestion-services/mqtt-cert

patchesStrategicMerge:
  - all-minikube.yaml