version: '3'

networks:
  esthesis-dev:

services:
  esthesis-db:
    image: mysql:8.0.16
    hostname: esthesis-db
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --max_allowed_packet=1024000000
    ports:
      - ${DB_PORT}:3306
    environment:
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
    networks:
      - esthesis-dev

  esthesis-mqtt:
    image: eclipse-mosquitto:1.6.12
    hostname: esthesis-mqtt
    restart: unless-stopped
    ports:
      - "${PORT_MQTT}:1883"
      - "${PORT_MQTT_SECURE}:8883"
    healthcheck:
      test: nc -vz localhost 1883 || nc -vz localhost 8883
    networks:
      - esthesis-dev

  esthesis-influxdb:
    image: influxdb:1.7.8
    hostname: esthesis-influxdb
    restart: unless-stopped
    ports:
      - ${PORT_INFLUXDB}:8086
    environment:
      - INFLUXDB_DB
      - INFLUXDB_ADMIN_USER
      - INFLUXDB_ADMIN_PASSWORD
    healthcheck:
      test: curl -sI 127.0.0.1:8086/ping | grep -q "204 No Content"
    networks:
      - esthesis-dev

  esthesis-nifi:
    image: esthesis/esthesis-docker-nifi:1.10.0-2
    hostname: esthesis-nifi
    restart: unless-stopped
    ports:
      - "${NIFI_WEB_UI}:8080"
      - "${NIFI_WEB_PRODUCER_PORT}:20000"
    healthcheck:
      test: curl -sI http://esthesis-nifi:8080/nifi | grep -q "HTTP/1.1 302 Found"
    networks:
      - esthesis-dev

  esthesis-chronograf:
    image: chronograf:1.7.8
    hostname: esthesis-chronograf
    restart: unless-stopped
    ports:
      - "${PORT_SINK_INFLUXDB_CHRONOGRAF}:8888"
    command: --influxdb-url=http://esthesis-influxdb:8086
    networks:
      - esthesis-dev

  esthesis-syslog:
    image: pbertera/syslogserver
    hostname: esthesis-syslog
    restart: unless-stopped
    ports:
      - "${PORT_SYSLOG_WEB}:80"
      - "${PORT_SYSLOG_UDP}:514/udp"
    environment:
      - SYSLOG_USERNAME=admin
      - SYSLOG_PASSWORD=admin
    networks:
      - esthesis-dev
