---
apiVersion: v1
kind: Service
metadata:
  name: esthesis-ps-db-service
spec:
  selector:
    app: esthesis-ps-db
  ports:
    - port: 3306
      nodePort: 30000
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: esthesis-ps-db-monitor-service
spec:
  selector:
    app: esthesis-ps-db-monitor
  ports:
    - port: 80
      nodePort: 30001
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: esthesis-ds-influxdb-service
spec:
  selector:
    app: esthesis-ds-influxdb
  ports:
    - port: 8086
      name: http
      nodePort: 30002
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: esthesis-ds-influxdb-monitor-service
spec:
  selector:
    app: esthesis-ds-influxdb-monitor
  ports:
    - port: 8888
      nodePort: 30003
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: esthesis-ds-mysql-service
spec:
  selector:
    app: esthesis-ds-mysql
  ports:
    - port: 3306
      nodePort: 30004
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: esthesis-ds-mysql-monitor-service
spec:
  selector:
    app: esthesis-ds-mysql-monitor
  ports:
    - port: 80
      nodePort: 30005
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: esthesis-is-mqtt-cert-service
spec:
  selector:
    app: esthesis-is-mqtt-cert
  ports:
    - port: 1883
      nodePort: 30006
  type: NodePort