apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../platform-services
  - ../../datasinks
  - ../../ingestion-services/mqtt

patchesStrategicMerge:
  - all-minikube-dev.yaml
