####################################################################################################
# esthesis-ds-mysql-backup
# Backup container for MySQL
####################################################################################################

####################################################################################################
# Configmap
####################################################################################################
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: esthesis-ds-mysql-backup-config
data:
  backup-file: |
    #!/bin/sh
    echo "Started: $(date)"
    echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
    echo "Backups before:"
    ls -aslR /backup
    echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
    echo Backup file: "$1.sql"
    /usr/bin/mysqldump -u root -proot -h esthesis-ds-mysql-service esthesis --single-transaction --quick --lock-tables=false > $1.sql
    tar cvfz $1.tar.gz $1.sql
    rm -rf $1.sql
    echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
    echo Deleting old backups
    find /backup -type f -mtime +30 -exec rm {} \;
    echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
    echo "Backups after:"
    ls -aslR /backup
    echo "Finished: $(date)"

####################################################################################################
# PVC
####################################################################################################
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esthesis-ds-mysql-backup-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi

####################################################################################################
# Deployment
####################################################################################################
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: esthesis-ds-mysql-backup
spec:
  schedule: "@daily"
  concurrencyPolicy: "Forbid"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: esthesis-ds-mysql-backup
              image: mysql:8.0.16
              command:
                - "/bin/sh"
                - "-c"
                - "/opt/backup/backup.sh /backup/$(date +%Y%m%d%H%M%S)"
              volumeMounts:
                - name: esthesis-ds-mysql-backup-pv
                  mountPath: "/backup"
                - name: backup-script
                  mountPath: /opt/backup
          restartPolicy: "Never"
          volumes:
            - name: esthesis-ds-mysql-backup-pv
              persistentVolumeClaim:
                claimName: esthesis-ds-mysql-backup-pvc
            - name: backup-script
              configMap:
                name: esthesis-ds-mysql-backup-config
                defaultMode: 0777
                items:
                  - key: "backup-file"
                    path: "backup.sh"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3