####################################################################################################
# esthesis-ps-db
# A MySQL database to be used as the main database for the platform backend.
####################################################################################################

####################################################################################################
# Secrets
####################################################################################################
---
apiVersion: v1
kind: Secret
metadata:
  name: esthesis-ps-db-secrets
type: Opaque
stringData:
  # The password for the root user used by the MySQL database of esthesis platform.
  MYSQL_ROOT_PASSWORD: "root"

####################################################################################################
# Configmap
####################################################################################################
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: esthesis-ps-db-config
data:
  # The maximum packet allowed allowed for esthesis platform MySQL database.
  MAX_ALLOWED_PACKET: "1024000000"

####################################################################################################
# PVC
####################################################################################################
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esthesis-ps-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: $STORAGECLASS

####################################################################################################
# MySQL service
####################################################################################################
---
apiVersion: v1
kind: Service
metadata:
  name: esthesis-ps-db-service
spec:
  selector:
    app: esthesis-ps-db
  ports:
    - port: 3306

####################################################################################################
# MySQL service deployment
####################################################################################################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: esthesis-ps-db-deployment
spec:
  selector:
    matchLabels:
      app: esthesis-ps-db
  replicas: 1
  template:
    metadata:
      labels:
        app: esthesis-ps-db
    spec:
      containers:
        - name: esthesis-ps-db
          image: mysql:8.0.16
          args:
            - "--default-authentication-plugin=mysql_native_password"
            - "--max_allowed_packet=$(MAX_ALLOWED_PACKET)"
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: esthesis-ps-db-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: MAX_ALLOWED_PACKET
              valueFrom:
                configMapKeyRef:
                  name: esthesis-ps-db-config
                  key: MAX_ALLOWED_PACKET
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              name: esthesis-ps-db-pv
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 30
            periodSeconds: 30
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 90
            periodSeconds: 15
            failureThreshold: 2
      volumes:
        - name: esthesis-ps-db-pv
          persistentVolumeClaim:
            claimName: esthesis-ps-db-pvc