apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: esthesis-ingress-platform-ui
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: platform.nassos1.dev.ath.esthesis.cloud
      http:
        paths:
          - path: /
            backend:
              serviceName: esthesis-platform-ui-service
              servicePort: 80
  tls:
    - hosts:
        - platform.nassos1.dev.ath.esthesis.cloud
      secretName: platform-nassos1-dev-ath-esthesis-cloud-crt