####################################################################################################
# esthesis-ds-influxdb-monitor
# A Chronograf frontend for the InfluxDB data sink.
####################################################################################################

####################################################################################################
# Secrets
####################################################################################################
---
apiVersion: v1
kind: Secret
metadata:
  name: esthesis-ds-influxdb-monitor-secrets
type: Opaque
stringData:
  # The password for the root user used by the MySQL database of esthesis platform.
  MYSQL_ROOT_PASSWORD: "root"

####################################################################################################
# Configmap
####################################################################################################
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: esthesis-ds-influxdb-monitor-config
data:
  PMA_HOST: "esthesis-ds-mysql-service"
  PMA_USER: "root"

####################################################################################################
# Service
####################################################################################################
---
apiVersion: v1
kind: Service
metadata:
  name: esthesis-ds-influxdb-monitor-service
spec:
  selector:
    app: esthesis-ds-influxdb-monitor
  ports:
    - port: 8888

####################################################################################################
# Deployment
####################################################################################################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: esthesis-ds-influxdb-monitor-deployment
spec:
  selector:
    matchLabels:
      app: esthesis-ds-influxdb-monitor
  replicas: 1
  template:
    metadata:
      labels:
        app: esthesis-ds-influxdb-monitor
    spec:
      containers:
        - name: esthesis-ds-influxdb-monitor
          image: chronograf:1.7.8
          args:
            - "--influxdb-url=http://esthesis-ds-influxdb:8086"
          ports:
            - containerPort: 8888
          readinessProbe:
            httpGet:
              path: /
              port: 8888
            initialDelaySeconds: 30
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /
              port: 8888
            initialDelaySeconds: 45
            periodSeconds: 15
            failureThreshold: 2