####################################################################################################
# esthesis-ds-influxdb
# An instance of InfluxDB.
####################################################################################################

####################################################################################################
# Secrets
####################################################################################################
---
apiVersion: v1
kind: Secret
metadata:
  name: esthesis-ds-influxdb-secrets
type: Opaque
stringData:
  admin_password: "esthesis"

####################################################################################################
# Configmap
####################################################################################################
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: esthesis-ds-influxdb-config
data:
  admin_user: "esthesis"

####################################################################################################
# PVC
####################################################################################################
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esthesis-ds-influxdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: $STORAGECLASS

####################################################################################################
# Services (HTTP + RPC)
####################################################################################################
---
apiVersion: v1
kind: Service
metadata:
  name: esthesis-ds-influxdb-service
spec:
  selector:
    app: esthesis-ds-influxdb
  ports:
    - port: 8086
      name: http
      targetPort: 8086
    - port: 8088
      name: rpc
      targetPort: 8088

####################################################################################################
# Deployment
####################################################################################################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: esthesis-ds-influxdb-deployment
spec:
  selector:
    matchLabels:
      app: esthesis-ds-influxdb
  replicas: 1
  template:
    metadata:
      labels:
        app: esthesis-ds-influxdb
    spec:
      containers:
        - name: esthesis-ds-influxdb
          image: influxdb:1.7.5
          ports:
            - containerPort: 8086
            - containerPort: 8088
          env:
            - name: INFLUXDB_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: esthesis-ds-influxdb-secrets
                  key: admin_password
            - name: INFLUXDB_ADMIN_USER
              valueFrom:
                configMapKeyRef:
                  name: esthesis-ds-influxdb-config
                  key: admin_user
            - name: INFLUXDB_DB
              value: "esthesis"
            - name: INFLUXDB_BIND_ADDRESS
              value: ":8088"
          volumeMounts:
            - mountPath: "/var/lib/influxdb"
              name: esthesis-ds-influxdb-pv
          readinessProbe:
            httpGet:
              path: /ping
              port: 8086
            initialDelaySeconds: 30
            periodSeconds: 15
          livenessProbe:
              httpGet:
                path: /ping
                port: 8086
              initialDelaySeconds: 45
              periodSeconds: 15
              failureThreshold: 2
      volumes:
        - name: esthesis-ds-influxdb-pv
          persistentVolumeClaim:
            claimName: esthesis-ds-influxdb-pvc