####################################################################################################
# esthesis-ds-influxdb-backup
# Backup job for InfluxDB
####################################################################################################

####################################################################################################
# Configmap
####################################################################################################
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: esthesis-ds-influxdb-backup-config
data:
  backup-file: |
    #!/bin/sh
    echo "Started: $(date)"
    echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
    echo "Backups before:"
    ls -aslR /backup
    echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
    echo Backup folder: "$1"
    influxd backup -database esthesis -host esthesis-ds-influxdb-service:8088 $1
    tar cvfz $1.tar.gz $1
    rm -rf $1
    echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
    echo Deleting old backups
    find /backup -type f -mtime +30 -exec rm {} \;
    echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
    echo "Backups after:"
    ls -aslR /backup
    echo "Finished: $(date)"

####################################################################################################
# PVC
####################################################################################################
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esthesis-ds-influxdb-backup-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard

####################################################################################################
# Deployment
####################################################################################################
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: esthesis-ds-influxdb-backup
spec:
  schedule: "@daily"
  concurrencyPolicy: "Forbid"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: esthesis-ds-influxdb-backup
              image: influxdb:1.7.5-alpine
              command:
                - "/bin/sh"
                - "-c"
                - "/opt/backup/backup.sh /backup/$(date +%Y%m%d%H%M%S)"
              volumeMounts:
                - name: esthesis-ds-influxdb-backup-pv
                  mountPath: "/backup"
                - name: backup-script
                  mountPath: /opt/backup
          restartPolicy: "Never"
          volumes:
            - name: esthesis-ds-influxdb-backup-pv
              persistentVolumeClaim:
                claimName: esthesis-ds-influxdb-backup-pvc
            - name: backup-script
              configMap:
                name: esthesis-ds-influxdb-backup-config
                defaultMode: 0777
                items:
                  - key: "backup-file"
                    path: "backup.sh"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3