---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config
data:
  test-file: |
    #!/bin/sh
    A="test"
    echo "A is: $A"

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: test-cb
spec:
  schedule: "@daily"
  concurrencyPolicy: "Forbid"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: test-container
              image: busybox:1
              command:
                - "/opt/test/test.sh"
              volumeMounts:
                - name: test-script
                  mountPath: /opt/test
          restartPolicy: "Never"
          volumes:
            - name: test-script
              configMap:
                name: test-config
                defaultMode: 0777
                items:
                  - key: "test-file"
                    path: "test.sh"