version: '3'

networks:
  esthesis:

services:
  db:
    image: mysql:8.0.16
    hostname: esthesis-db
    container_name: esthesis-db
    restart: always
    command: --default-authentication-plugin=mysql_native_password --max_allowed_packet=1024000000
    ports:
      - "${PORT_DB}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - esthesis

  db_admin:
    image: phpmyadmin/phpmyadmin
    hostname: esthesis-db-admin
    container_name: esthesis-db-admin
    restart: always
    ports:
      - "${PORT_DB_ADMIN}:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - esthesis

  mail:
    image: djfarrelly/maildev
    hostname: esthesis-mail
    container_name: esthesis-mail
    restart: always
    ports:
      - "${PORT_MAIL_SMTP}:25"
      - "${PORT_MAIL_WEB}:80"
    networks:
      - esthesis

  mqtt:
    image: eclipse-mosquitto
    hostname: esthesis-mqtt
    container_name: esthesis-mqtt
    restart: always
    ports:
      - "${PORT_MQTT}:1883"
    networks:
      - esthesis

  zookeeper:
    image: zookeeper:3.5
    hostname: esthesis-zookeeper
    container_name: esthesis-zookeeper
    restart: always
    ports:
      - "${ZOOKEEPER_PORT}:2181"
    environment:
      ZOO_STANDALONE_ENABLED: "true"
    networks:
      - esthesis

  zoonavigator-web:
    image: elkozmon/zoonavigator-web
    container_name: esthesis-zoonavigator-web
    ports:
      - "8000:8000"
    environment:
      WEB_HTTP_PORT: 8000
      API_HOST: "esthesis-zoonavigator-api"
      API_PORT: 9000
      AUTO_CONNECT_CONNECTION_STRING: "esthesis-zookeeper:2181"
    depends_on:
      - zoonavigator-api
    restart: always
    networks:
      - esthesis

  zoonavigator-api:
    image: elkozmon/zoonavigator-api
    container_name: esthesis-zoonavigator-api
    environment:
      API_HTTP_PORT: 9000
    restart: always
    networks:
      - esthesis

###############################################################################
# Data sinks
###############################################################################
  sink-influxdb:
    image: influxdb:1.7.5
    hostname: sink-influxdb
    container_name: esthesis-sink-influxdb
    restart: always
    ports:
      - "${PORT_SINK_INFLUXDB}:8086"
    environment:
      - INFLUXDB_DB=esthesis
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    networks:
      - esthesis

  sink-influxdb-chronograf:
    image: chronograf:1.7.8
    hostname: sink-influxdb-chronograf
    container_name: esthesis-sink-chronograf
    restart: always
    ports:
      - "${PORT_SINK_INFLUXDB_CHRONOGRAF}:8888"
    command: --influxdb-url=http://sink-influxdb:8086
    networks:
      - esthesis

  sink-mysql:
    image: mysql:8.0.13
    hostname: sink-mysql
    container_name: esthesis-sink-mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "${PORT_SINK_MYSQL}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - esthesis
