####################################################################################################
# esthesis global configuration and secrets
####################################################################################################
# Define secrets.
apiVersion: v1
kind: Secret
metadata:
  name: esthesis-secrets
type: Opaque
stringData:
  # The password for the root user used by the MySQL database of esthesis platform.
  esthesis-is-platform-db__MYSQL_ROOT_PASSWORD: "root"
  # The JWT secret used in signing JWT for the front-end to back-end communication.
  esthesis-platform-server__esthesis.jwt_secret: "V4h67m2xsHZmBPbcT2pTAWLZdr8SqbLv3ZZhjJKs3DPv9ww5T7LfqftUdbUGtpKk"
  # The password of the user esthesis platform uses to connect to the database. This should, obviously,
  # be the same as esthesis-is-platform-db_MYSQL_ROOT_PASSWORD.
  esthesis-platform-server__spring.datasource.password: "root"

# Define config maps.
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: esthesis-config
data:
  # The maximum packet allowed allowed for esthesis platform MySQL database.
  esthesis-is-platform-db__max_allowed_packet: "1024000000"
  # The JDBC URL esthesis platform uses to conenct to the database.
  esthesis-platform-server__spring.datasource.url: "jdbc:mysql://esthesis-is-platform-db-service:3306/esthesis?autoReconnect=true&createDatabaseIfNotExist=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&maxReconnects=10"
  # The username of the user esthesis platform uses to connect to the database.
  esthesis-platform-server__spring.datasource.username: "root"