version: '3'

volumes:
  VOL_DB:
  VOL_ZOOKEEPER_DATA:
  VOL_ZOOKEEPER_LOG:
  VOL_SINK_INFLUX:
  VOL_UTIL_CHRONOGRAF:
  VOL_PLATFORM_SERVER:
  VOL_CHRONOGRAF:

services:
  esthesis-db:
    image: mysql:8.0.16
    hostname: esthesis-db
    command: --default-authentication-plugin=mysql_native_password --max_allowed_packet=1024000000
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - "VOL_DB:/var/lib/mysql"

  esthesis-zookeeper:
    image: zookeeper:3.5
    hostname: esthesis-zookeeper
    environment:
      ZOO_STANDALONE_ENABLED: "true"
    volumes:
      - "VOL_ZOOKEEPER_DATA:/data"
      - "VOL_ZOOKEEPER_LOG:/datalog"

  esthesis-sink-influxdb:
    image: influxdb:1.7.5
    hostname: esthesis-sink-influxdb
    environment:
      - INFLUXDB_DB=esthesis
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    volumes:
      - "VOL_SINK_INFLUX:/var/lib/influxdb"

  esthesis-util-chronograf:
    image: chronograf:1.7.8
    hostname: esthesis-util-chronograf
    command: --influxdb-url=http://esthesis-sink-influxdb:8086
    ports:
      - "${CHRONOGRAF_PORT}:8888"
    volumes:
      - "VOL_CHRONOGRAF:/var/lib/chronograf"

  esthesis-platform-server:
    image: esthesis/platform-server
    hostname: esthesis-platform-server
    environment:
      - spring.datasource.url=jdbc:mysql://esthesis-db:3306/esthesis?autoReconnect=true&createDatabaseIfNotExist=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&maxReconnects=1000
    volumes:
      - "VOL_PLATFORM_SERVER:/app/esthesis"

  esthesis-platform-ui:
    image: esthesis/platform-ui
    hostname: esthesis-platform-ui
    ports:
      - "$PLATFORM_PORT:80"