###############################################################################
# esthesis test container
###############################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: esthesis-test-deployment
spec:
  selector:
    matchLabels:
      app: esthesis-test
  replicas: 1
  template:
    metadata:
      labels:
        app: esthesis-test
    spec:
      containers:        
        - name: esthesis-test
          image: busybox
          command: [ "/bin/sh", "-c", "--" ]
          args: [ "trap : TERM INT; (while true; do sleep 1000; done) & wait" ]
