####################################################################################################
# esthesis services
#
# esthesis platform MySQL database
####################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: esthesis-is-platform-db-service
spec:
  selector:
    app: esthesis-is-platform-db
  ports:
    - port: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: esthesis-is-platform-db-deployment
spec:
  selector:
    matchLabels:
      app: esthesis-is-platform-db
  replicas: 1
  template:
    metadata:
      labels:
        app: esthesis-is-platform-db
    spec:
      containers:
        - name: esthesis-is-platform-db
          image: mysql:8.0.16
          args:
            - "--default-authentication-plugin=mysql_native_password"
            - "--max_allowed_packet=$(MAX_ALLOWED_PACKET)"
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: esthesis-secrets
                  key: esthesis-is-platform-db__MYSQL_ROOT_PASSWORD
            - name: MAX_ALLOWED_PACKET
              valueFrom:
                configMapKeyRef:
                  name: esthesis-config
                  key: esthesis-is-platform-db__max_allowed_packet
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 30
            periodSeconds: 30
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 90
            periodSeconds: 15
            failureThreshold: 2