####################################################################################################
# esthesis-platform-ui
# The frontend component of esthesis platform.
####################################################################################################

####################################################################################################
# Service
####################################################################################################
---
apiVersion: v1
kind: Service
metadata:
  name: esthesis-platform-ui-service
spec:
  selector:
    app: esthesis-platform-ui
  ports:
    - port: 80

####################################################################################################
# Deployment
####################################################################################################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: esthesis-platform-ui-deployment
spec:
  selector:
    matchLabels:
      app: esthesis-platform-ui
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: esthesis-platform-ui
    spec:
      containers:
        - name: esthesis-platform-ui
          image: esthesis/esthesis-platform-ui
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 45
            periodSeconds: 15
            failureThreshold: 2
      imagePullSecrets:
        - name: esthesis-dockerhub