####################################################################################################
# esthesis-platform-server
# The main backend component of esthesis platform.
####################################################################################################

####################################################################################################
# Secrets
####################################################################################################
---
apiVersion: v1
kind: Secret
metadata:
  name: esthesis-platform-server-secrets
type: Opaque
stringData:
  # The JWT secret used in signing JWT for the front-end to back-end communication.
  esthesis.jwt_secret: "V4h67m2xsHZmBPbcT2pTAWLZdr8SqbLv3ZZhjJKs3DPv9ww5T7LfqftUdbUGtpKk"
  # The password of the user esthesis platform uses to connect to the database. This should, obviously,
  # be the same as esthesis-is-platform-db_MYSQL_ROOT_PASSWORD.
  spring.datasource.password: "root"

####################################################################################################
# Configmap
####################################################################################################
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: esthesis-platform-server-config
data:
  # The JDBC URL esthesis platform uses to conenct to the database.
  spring.datasource.url: "jdbc:mysql://esthesis-ps-db-service:3306/esthesis?autoReconnect=true&createDatabaseIfNotExist=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&maxReconnects=10"
  # The username of the user esthesis platform uses to connect to the database.
  spring.datasource.username: "root"

####################################################################################################
# PVC
####################################################################################################
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esthesis-platform-server-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: $STORAGECLASS

####################################################################################################
# Service
####################################################################################################
---
apiVersion: v1
kind: Service
metadata:
  name: esthesis-platform-server-service
spec:
  selector:
    app: esthesis-platform-server
  ports:
    - port: 46000

####################################################################################################
# Deployment
####################################################################################################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: esthesis-platform-server-deployment
spec:
  selector:
    matchLabels:
      app: esthesis-platform-server
  replicas: 1
  template:
    metadata:
      labels:
        app: esthesis-platform-server
    spec:
      containers:
        - name: esthesis-platform-server
          image: $REGISTRY/esthesis-platform-server
          ports:
            - containerPort: 46000
          env:
            - name: spring.datasource.url
              valueFrom:
                configMapKeyRef:
                  name: esthesis-platform-server-config
                  key: spring.datasource.url
            - name: esthesis.fsRoot
              value: "/data"
            - name: esthesis.jwt_secret
              valueFrom:
                secretKeyRef:
                  name: esthesis-platform-server-secrets
                  key: esthesis.jwt_secret
            - name: spring.datasource.username
              valueFrom:
                configMapKeyRef:
                  name: esthesis-platform-server-config
                  key: spring.datasource.username
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: esthesis-platform-server-secrets
                  key: spring.datasource.password
          volumeMounts:
            - mountPath: "/data"
              name: esthesis-platform-server-pv
          readinessProbe:
            httpGet:
              path: /api/ping
              port: 46000
            initialDelaySeconds: 60
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /api/ping
              port: 46000
            initialDelaySeconds: 120
            periodSeconds: 30
            failureThreshold: 2
      volumes:
        - name: esthesis-platform-server-pv
          persistentVolumeClaim:
            claimName: esthesis-platform-server-pvc